[profile.default]
solc_version = "0.8.24"

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/",
]

[fmt]
line_length = 100

[profile.via-ir]
via_ir = true